name: vietmall
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  firebase_storage: ^11.7.5

  # UI & State Management
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  carousel_slider: 5.0.0
  # image_picker: ^1.0.7  <-- XÓA DÒNG NÀY
  # path: ^1.8.3          <-- XÓA DÒNG NÀY

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/