// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSkNONlW_bK0Z6tvnw-7HedgOlxJKRTf0',
    appId: '1:790027490237:web:6170f165389522d0fff8d4',
    messagingSenderId: '790027490237',
    projectId: 'vietmall-app',
    authDomain: 'vietmall-app.firebaseapp.com',
    storageBucket: 'vietmall-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfQOuXuCG7bzB_rcR86ws8R1tazel5nQg',
    appId: '1:790027490237:android:cc6cb06088c17fe7fff8d4',
    messagingSenderId: '790027490237',
    projectId: 'vietmall-app',
    storageBucket: 'vietmall-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKAvMfUxq51d4oeFzAkb1tlD3edhyg2PQ',
    appId: '1:790027490237:ios:f707e2eee265f7f4fff8d4',
    messagingSenderId: '790027490237',
    projectId: 'vietmall-app',
    storageBucket: 'vietmall-app.firebasestorage.app',
    iosBundleId: 'com.example.vietmall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKAvMfUxq51d4oeFzAkb1tlD3edhyg2PQ',
    appId: '1:790027490237:ios:f707e2eee265f7f4fff8d4',
    messagingSenderId: '790027490237',
    projectId: 'vietmall-app',
    storageBucket: 'vietmall-app.firebasestorage.app',
    iosBundleId: 'com.example.vietmall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSkNONlW_bK0Z6tvnw-7HedgOlxJKRTf0',
    appId: '1:790027490237:web:74723bd287275854fff8d4',
    messagingSenderId: '790027490237',
    projectId: 'vietmall-app',
    authDomain: 'vietmall-app.firebaseapp.com',
    storageBucket: 'vietmall-app.firebasestorage.app',
  );
}
